// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    var defaultParams, settings, syncURL;
    if (!settings in window) {
      window.alert("ERROR! Must set settings.js -- see README");
      throw "ERROR! Must set settings.js -- see README";
    }
    settings = window.settings;
    syncURL = settings.apiBase + "sync";
    defaultParams = {
      token: settings.apiKey,
      seq_no: 0,
      seq_no_global: 0,
      resource_types: JSON.stringify(["projects"])
    };
    return $(window).bind("keydown", settings.saveToProjectBind, function(e) {
      var activeURL, syncParams;
      activeURL = window.location.href;
      syncParams = defaultParams;
      $.getJSON(syncURL, syncParams, function(response) {
        var i, len, p, project, ref;
        syncParams.seq_no = response.seq_no;
        syncParams.seq_no_global = response.seq_no_global;
        project = null;
        ref = response.Projects;
        for (i = 0, len = ref.length; i < len; i++) {
          p = ref[i];
          if (p.name === settings.projectName) {
            project = p;
            break;
          }
        }
        if (project) {
          delete syncParams.resource_types;
          delete syncParams.seq_no;
          delete syncParams.seq_no_global;
          syncParams.commands = JSON.stringify([
            {
              type: "item_add",
              temp_id: "0",
              uuid: "b28eea80-3e29-11e5-b970-0800200c9a66",
              args: {
                project_id: project.id,
                content: activeURL,
                date_string: null
              }
            }
          ]);
          return $.getJSON(syncURL, syncParams, function(response) {
            syncParams.seq_no = response.seq_no;
            syncParams.seq_no_global = response.seq_no_global;
            return window.alert("SUCCESS!");
          });
        }
      });
      return false;
    });
  })(jQuery);

}).call(this);
