// Generated by CoffeeScript 1.9.3
(function() {
  (function($) {
    return document.addEventListener("DOMContentLoaded", function() {
      var button, enterKey, input, sendInputToActiveContentScript;
      input = $(".inputText");
      button = $(".submitButton");
      enterKey = 13;
      button.click(function() {
        var text;
        text = input.val();
        input.val("");
        return sendInputToActiveContentScript(text);
      });
      input.keypress(function(e) {
        var key, text;
        key = e.which;
        if (key === enterKey) {
          text = input.val();
          input.val("");
          return sendInputToActiveContentScript(text);
        }
      });
      return sendInputToActiveContentScript = function(input) {
        return chrome.tabs.query({
          active: true,
          lastFocusedWindow: true
        }, function(tabs) {
          return chrome.tabs.sendMessage(tabs[0].id, {
            input: input
          });
        });
      };
    });
  })(jQuery);

}).call(this);
